part1: part1.cpp snappy/build/libsnappy.a
	g++ part1.cpp snappy/build/libsnappy.a -o part1

opt: part1.cpp snappy/build/libsnappy.a
	g++ -O3 part1.cpp snappy/build/libsnappy.a -o part1

clean:
	rm -rf part1
